//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_book_management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbBookEntities1 : DbContext
    {
        public dbBookEntities1()
            : base("name=dbBookEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_author> tbl_author { get; set; }
        public virtual DbSet<tbl_book> tbl_book { get; set; }
        public virtual DbSet<tbl_booktype> tbl_booktype { get; set; }
        public virtual DbSet<tbl_publisher> tbl_publisher { get; set; }
    }
}
