//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_book_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_book
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public Nullable<int> booktype_id { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> pub_id { get; set; }
        public string book_pub_date { get; set; }
        public string ISBN_No { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual tbl_author tbl_author { get; set; }
        public virtual tbl_booktype tbl_booktype { get; set; }
        public virtual tbl_publisher tbl_publisher { get; set; }
    }
}
