//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_book_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_author()
        {
            this.tbl_book = new HashSet<tbl_book>();
        }
    
        public int author_id { get; set; }
        public string author_name { get; set; }
        public string author_email { get; set; }
        public Nullable<int> booktype_id { get; set; }
        public Nullable<int> phone { get; set; }
        public string password { get; set; }
    
        public virtual tbl_booktype tbl_booktype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_book> tbl_book { get; set; }
    }
}
